"use client";

import { useEffect, useState } from "react";
import { codeToHtml } from "shiki";

interface CodeBlockClientProps {
	code: string;
	language?: string;
	showCopyButton?: boolean;
}

export function CodeBlockClient({
	code,
	language = "tsx",
}: CodeBlockClientProps) {
	const [html, setHtml] = useState<string>("");
	const [isLoading, setIsLoading] = useState(true);

	useEffect(() => {
		async function highlightCode() {
			setIsLoading(true);
			try {
				const highlighted = await codeToHtml(code, {
					lang: language,
					themes: {
						light: "github-light",
						dark: "github-dark",
					},
					transformers: [
						{
							pre(node) {
								node.properties.tabindex = undefined;
							},
							code(node) {
								node.properties.style = undefined;
							},
						},
					],
				});
				setHtml(highlighted);
			} catch (error) {
				console.error("Failed to highlight code:", error);
			} finally {
				setIsLoading(false);
			}
		}

		highlightCode();
	}, [code, language]);

	if (isLoading) {
		return (
			<div className="relative bg-muted/30 p-6">
				<div className="h-24 animate-pulse rounded bg-muted" />
			</div>
		);
	}

	return (
		<div
			className="overflow-x-auto bg-muted/30 p-6 font-mono text-sm [&_code]:bg-transparent [&_pre]:m-0 [&_pre]:overflow-visible [&_pre]:bg-transparent [&_pre]:p-0"
			// biome-ignore lint/security/noDangerouslySetInnerHtml: HTML is generated by shiki syntax highlighter
			dangerouslySetInnerHTML={{ __html: html }}
		/>
	);
}
